-- liquibase formatted sql

-- changeset salimgareeva:1
CREATE SCHEMA IF NOT EXISTS category;
create table if not exists category(
    title          TEXT primary key,
    parent_title         TEXT
);

-- changeset salimgareeva:2
CREATE SCHEMA IF NOT EXISTS document;
CREATE TABLE IF NOT EXISTS document
(
    id                      BIGINT generated by default as identity primary key,
    file_path               TEXT NOT NULL,
    file_size               BIGINT NOT NULL,
    media_type              TEXT NOT NULL,
    data                    BYTEA NOT NULL

);
